name = "remix-cloudflare-workers-template"

main = "./server.ts"
workers_dev = true
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"

kv_namespaces = [{ binding = "WORKER2_KV", id = "local-worker2" }]

[site]
bucket = "./build/client"

[build]
command = "npm run build"

[env.local]
kv_namespaces = [{ binding = "WORKER2_KV", id = "local-worker2" }]
